"""empty message

Revision ID: 6a0699ffd9d3
Revises: c3bba73741b3
Create Date: 2021-06-01 00:07:10.094021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0699ffd9d3'
down_revision = 'c3bba73741b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_residencias', sa.Column('like', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_residencias', 'like')
    # ### end Alembic commands ###
