"""empty message

Revision ID: c3bba73741b3
Revises: 
Create Date: 2021-05-31 22:10:23.502412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3bba73741b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_residencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host_id', sa.String(length=255), nullable=False),
    sa.Column('host_name', sa.String(length=255), nullable=False),
    sa.Column('neighbourhood', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.String(length=255), nullable=False),
    sa.Column('longitude', sa.String(length=255), nullable=False),
    sa.Column('room_type', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=255), nullable=False),
    sa.Column('minimum_nights', sa.String(length=255), nullable=False),
    sa.Column('number_of_reviews', sa.String(length=255), nullable=False),
    sa.Column('last_review', sa.String(length=255), nullable=False),
    sa.Column('reviews_per_month', sa.String(length=255), nullable=False),
    sa.Column('calculated_host_listings_count', sa.String(length=255), nullable=False),
    sa.Column('availability_365', sa.String(length=255), nullable=False),
    sa.Column('neighbourhood_group', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_residencias')
    # ### end Alembic commands ###
